from app.services.analysis_service import AnalysisService
from app.services.application_service import ApplicationService
from app.services.interview_service import InterviewService
from app.services.written_test_service import WrittenTestService
from app.services.skill_profile_service import SkillProfileService
